# Generated by Django 5.2.6 on 2026-03-17 15:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_assignment_image_assignment_subject_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subjecttask',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.subject'),
        ),
    ]
